import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Header, Footer, Banner } from "../components/index";

const Blog = () => {
    const articles = [
        {
            id: 1,
            category: "Protocol Update",
            date: "February 15, 2026",
            title: "AMERO X Airdrop Campaign — How to Claim Your Free AMX Tokens",
            excerpt: "We are excited to announce the AMERO X Airdrop Campaign. Eligible participants can claim free AMX tokens by completing simple social media verification tasks. Learn how to participate and secure your allocation before the distribution window closes.",
            readTime: "4 min read",
            content: [
                "The AMERO X team is thrilled to announce the launch of our community airdrop campaign — a key milestone in our mission to distribute AMX tokens to early supporters and active community members worldwide.",
                "To participate, users must connect their Web3 wallet (MetaMask or compatible), navigate to the Airdrop page, and complete three simple social media verification tasks: post on X (Twitter), Instagram, and LinkedIn using the provided description. Once all verifications are confirmed on-chain, your AMX tokens are instantly credited to your wallet.",
                "This airdrop is designed to reward genuine community engagement and build a strong, decentralized holder base ahead of our mainnet launch. Each participant receives a fixed allocation of AMX tokens, and the campaign will remain active until the airdrop contract balance is fully distributed.",
                "Important: Make sure your account is set to public during verification. Private accounts cannot be verified by our system. Also ensure you copy the exact description text provided in the Post Details section to pass the hashtag matching verification.",
            ],
        },
        {
            id: 2,
            category: "Technology",
            title: "Understanding Hybrid Order Matching: The Engine Behind AMERO X",
            date: "February 10, 2026",
            excerpt: "AMERO X's hybrid order matching engine combines the speed of off-chain signing with the security of on-chain settlement. Discover how this architecture delivers institutional-grade performance without sacrificing decentralization.",
            readTime: "6 min read",
            content: [
                "At the core of every exchange is an order matching engine — the system that pairs buyers with sellers. Traditional centralized exchanges process orders at lightning speed but at the cost of user sovereignty. Fully on-chain DEXs preserve decentralization but suffer from high latency, front-running, and prohibitive gas costs.",
                "AMERO X solves this dilemma with a Hybrid Order Matching Engine that achieves the best of both worlds. Orders are signed off-chain using EIP-712 typed signatures, enabling sub-second matching without any gas cost. Once matched, settlement occurs deterministically on-chain through our smart contract infrastructure on BNB Smart Chain.",
                "This architecture eliminates MEV (Miner Extractable Value) attacks, ensures all settlements are cryptographically verifiable, and delivers throughput comparable to centralized exchanges while maintaining full self-custody of user assets.",
                "The result: institutional-grade execution speed with zero counterparty risk — the standard AMERO X is setting for the next generation of decentralized finance.",
            ],
        },
        {
            id: 3,
            category: "Ecosystem",
            title: "Real Yield vs. Inflationary Rewards: Why AMERO X Chooses Revenue Sharing",
            date: "February 5, 2026",
            excerpt: "Unlike protocols that mint tokens as rewards, AMERO X distributes 30% of real protocol fees in USDC directly to AMX stakers. Learn why sustainable yield models are the future of DeFi.",
            readTime: "5 min read",
            content: [
                "The DeFi space has been plagued by unsustainable tokenomics. Many protocols incentivize participation by minting new tokens — a mechanism that dilutes existing holders, creates constant sell pressure, and ultimately destroys value. This inflationary model is fundamentally broken.",
                "AMERO X takes a radically different approach with Real Yield. Instead of printing tokens, we distribute 30% of actual protocol revenue — collected from trading fees, escrow fees, and settlement charges — directly to AMX stakers in USDC.",
                "This means every staking reward you earn represents real economic value generated by the protocol, not inflated token emissions. As protocol usage grows, staker rewards grow proportionally — creating a virtuous cycle of value creation.",
                "Real Yield aligns incentives between the protocol and its stakeholders. When the protocol succeeds, holders succeed. There are no emissions schedules, no vesting cliffs for phantom rewards, and no dilution. Just revenue, distributed transparently on-chain.",
                "This is not a theoretical model — it is the foundational economic design of AMERO X, engineered to deliver sustainable, long-term value to every participant in the ecosystem.",
            ],
        },
        {
            id: 4,
            category: "Security",
            title: "Sovereign Account Abstraction: How AMERO X Protects Your Assets",
            date: "January 28, 2026",
            excerpt: "AMERO X implements Social MPC-based account abstraction, providing institutional-grade security while maintaining zero onboarding friction. Your keys, your tokens — always.",
            readTime: "5 min read",
            content: [
                "Security in DeFi has always been a tradeoff: either you manage your own private keys (complex and risky for non-technical users) or you trust a custodian (defeating the purpose of decentralization). AMERO X eliminates this tradeoff with Sovereign Account Abstraction.",
                "Our implementation uses Social Multi-Party Computation (MPC) to split key management across multiple secure nodes. No single party — not even AMERO X — ever has access to your complete private key. Reconstruction requires multi-factor authentication from the user.",
                "For end users, this means a seamless onboarding experience. You can create an account using social login (Google, Apple, etc.) and immediately start transacting — no seed phrases to memorize, no hardware wallets required. Yet behind the scenes, your assets are protected by the same cryptographic standards used by institutional custodians.",
                "This is what we mean by Sovereign: you maintain absolute control over your assets with zero trust assumptions, while enjoying the simplicity of a Web2 user experience.",
            ],
        },
        {
            id: 5,
            category: "Partnerships",
            title: "Building the Institutional Bridge: AMERO X's Strategic Vision",
            date: "January 20, 2026",
            excerpt: "From Covent Garden, London to the global blockchain ecosystem — AMERO X is forging partnerships that bring traditional finance and DeFi closer together than ever before.",
            readTime: "4 min read",
            content: [
                "AMERO X was founded with a clear mission: to build the bridge between traditional institutional finance and the decentralized economy. This isn't just a technical challenge — it's a strategic one that requires deep partnerships across the financial value chain.",
                "Headquartered at 71-75 Shelton Street, Covent Garden, London, AMERO X is uniquely positioned at the intersection of one of the world's leading financial centres and the cutting edge of blockchain technology.",
                "Our partnership strategy focuses on three pillars: Technology (blockchain infrastructure providers and security auditors), Liquidity (institutional market makers and DEX aggregators), and Compliance (regulatory advisors and identity verification partners).",
                "Together, these partnerships ensure that AMERO X can deliver institutional-grade execution, deep liquidity, and regulatory compliance — the three prerequisites for mainstream institutional adoption of decentralized finance.",
            ],
        },
        {
            id: 6,
            category: "Community",
            title: "Join the AMERO X Movement: Community Governance Coming Soon",
            date: "January 12, 2026",
            excerpt: "AMERO X believes in decentralized governance. We're building the tools to give AMX holders a direct voice in protocol decisions, fee structures, and strategic direction.",
            readTime: "3 min read",
            content: [
                "Decentralization isn't just about technology — it's about governance. A truly decentralized protocol must give its community a meaningful voice in shaping its future. AMERO X is committed to this principle.",
                "We are developing a comprehensive governance framework that will allow AMX token holders to propose and vote on key protocol decisions, including fee structures, new feature priorities, partnership approvals, and treasury allocations.",
                "Governance participation will be weighted by AMX stake, ensuring that those with the most skin in the game have proportional influence. All votes will be recorded immutably on-chain for full transparency.",
                "In the meantime, we encourage all community members to join our Discord, follow us on X (Twitter), and engage in discussions about the protocol's direction. Your voice matters — and soon, it will be encoded directly into the protocol itself.",
            ],
        },
    ];

    const [expandedArticle, setExpandedArticle] = React.useState(null);

    return (
        <div>
            <Head>
                <title>AMERO X - Blog</title>
                <meta name="description" content="Stay updated with the latest news, protocol updates, and insights from the AMERO X ecosystem." />
            </Head>
            <Header />
            <Banner title="Blog" type="Home" action="Blog" path="/" />

            <section style={{ padding: '100px 0', minHeight: '80vh', position: 'relative' }}>
                <div className="hero-glow-layer"></div>
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-lg-10">
                            <div style={{ textAlign: 'center', marginBottom: '60px' }}>
                                <h2 style={{ color: '#d4af37', marginBottom: '15px' }}>Latest from AMERO X</h2>
                                <p style={{ color: '#aaa', fontSize: '16px' }}>Protocol updates, insights, and ecosystem news from the team</p>
                            </div>

                            {/* Featured Article */}
                            <div style={{
                                background: 'linear-gradient(135deg, rgba(212,175,55,0.15) 0%, rgba(255,255,255,0.05) 100%)',
                                border: '1px solid rgba(212,175,55,0.25)',
                                borderRadius: '20px',
                                padding: '40px',
                                marginBottom: '40px',
                            }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}>
                                    <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
                                        <span style={{
                                            background: 'rgba(212,175,55,0.2)',
                                            color: '#d4af37',
                                            padding: '5px 14px',
                                            borderRadius: '20px',
                                            fontSize: '12px',
                                            fontWeight: '700',
                                            textTransform: 'uppercase',
                                            letterSpacing: '0.5px',
                                        }}>⭐ FEATURED</span>
                                        <span style={{
                                            background: 'rgba(212,175,55,0.15)',
                                            color: '#d4af37',
                                            padding: '4px 12px',
                                            borderRadius: '20px',
                                            fontSize: '11px',
                                            fontWeight: '600',
                                            textTransform: 'uppercase',
                                        }}>{articles[0].category}</span>
                                    </div>
                                    <span style={{ color: '#666', fontSize: '13px' }}>{articles[0].date}</span>
                                </div>
                                <h3 style={{ color: '#fff', fontSize: '24px', fontWeight: '700', marginBottom: '15px', lineHeight: '1.3' }}>{articles[0].title}</h3>
                                <p style={{ color: '#bbb', fontSize: '15px', lineHeight: '1.7', marginBottom: '20px' }}>{articles[0].excerpt}</p>
                                {expandedArticle === 0 ? (
                                    <div>
                                        {articles[0].content.map((para, pIdx) => (
                                            <p key={pIdx} style={{ color: '#999', fontSize: '14px', lineHeight: '1.8', marginBottom: '15px' }}>{para}</p>
                                        ))}
                                        <button onClick={() => setExpandedArticle(null)} style={{ background: 'none', border: '1px solid rgba(212,175,55,0.3)', color: '#d4af37', padding: '8px 20px', borderRadius: '8px', cursor: 'pointer', fontSize: '13px' }}>Show Less</button>
                                    </div>
                                ) : (
                                    <button onClick={() => setExpandedArticle(0)} style={{ background: 'none', border: '1px solid rgba(212,175,55,0.3)', color: '#d4af37', padding: '8px 20px', borderRadius: '8px', cursor: 'pointer', fontSize: '13px' }}>Read Full Article →</button>
                                )}
                            </div>

                            {/* Article Grid */}
                            <div className="row" style={{ rowGap: '25px' }}>
                                {articles.slice(1).map((article, idx) => (
                                    <div key={article.id} className="col-lg-6 col-md-6">
                                        <div style={{
                                            background: 'rgba(255,255,255,0.08)',
                                            border: '1px solid rgba(212,175,55,0.15)',
                                            borderRadius: '16px',
                                            padding: '28px',
                                            height: '100%',
                                            display: 'flex',
                                            flexDirection: 'column',
                                            transition: 'border-color 0.3s, transform 0.3s',
                                        }}
                                            onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.4)'; e.currentTarget.style.transform = 'translateY(-3px)'; }}
                                            onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.15)'; e.currentTarget.style.transform = 'translateY(0)'; }}
                                        >
                                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                                                <span style={{
                                                    background: 'rgba(212,175,55,0.15)',
                                                    color: '#d4af37',
                                                    padding: '4px 12px',
                                                    borderRadius: '20px',
                                                    fontSize: '11px',
                                                    fontWeight: '600',
                                                    textTransform: 'uppercase',
                                                    letterSpacing: '0.5px',
                                                }}>{article.category}</span>
                                                <span style={{ color: '#666', fontSize: '12px' }}>{article.readTime}</span>
                                            </div>

                                            <h3 style={{ color: '#fff', fontSize: '17px', fontWeight: '700', marginBottom: '12px', lineHeight: '1.4' }}>{article.title}</h3>
                                            <p style={{ color: '#999', fontSize: '13px', lineHeight: '1.6', marginBottom: '15px' }}>{article.excerpt}</p>

                                            {expandedArticle === idx + 1 ? (
                                                <div style={{ flex: 1 }}>
                                                    {article.content.map((para, pIdx) => (
                                                        <p key={pIdx} style={{ color: '#888', fontSize: '13px', lineHeight: '1.7', marginBottom: '12px' }}>{para}</p>
                                                    ))}
                                                    <button onClick={() => setExpandedArticle(null)} style={{ background: 'none', border: '1px solid rgba(212,175,55,0.3)', color: '#d4af37', padding: '6px 16px', borderRadius: '6px', cursor: 'pointer', fontSize: '12px', marginTop: '5px' }}>Show Less</button>
                                                </div>
                                            ) : (
                                                <div style={{ marginTop: 'auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                    <span style={{ color: '#666', fontSize: '12px' }}>{article.date}</span>
                                                    <button onClick={() => setExpandedArticle(idx + 1)} style={{ background: 'none', border: 'none', color: '#d4af37', fontSize: '13px', fontWeight: '600', cursor: 'pointer', padding: 0 }}>Read More →</button>
                                                </div>
                                            )}
                                        </div>
                                    </div>
                                ))}
                            </div>

                            {/* Newsletter CTA */}
                            <div style={{
                                background: 'rgba(212,175,55,0.06)',
                                border: '1px solid rgba(212,175,55,0.2)',
                                borderRadius: '16px',
                                padding: '40px',
                                textAlign: 'center',
                                marginTop: '50px',
                                position: 'relative',
                                zIndex: 10
                            }}>
                                <h3 style={{ color: '#d4af37', marginBottom: '12px' }}>Stay in the Loop</h3>
                                <p style={{ color: '#aaa', marginBottom: '25px', maxWidth: '450px', margin: '0 auto 25px' }}>Follow us on social media to never miss a protocol update or community announcement.</p>
                                <div style={{ display: 'flex', gap: '15px', justifyContent: 'center', flexWrap: 'wrap' }}>
                                    <a href="https://x.com/AmeroXchain" target="_blank" rel="noopener noreferrer" className="btn" style={{ fontSize: '14px' }}>Follow on X</a>
                                    <a href="https://discord.gg/AD4kkTMuJw" target="_blank" rel="noopener noreferrer" className="btn btn-two" style={{ fontSize: '14px' }}>Join Discord</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <Footer />
        </div>
    );
};

export default Blog;
